name: autobahn testsuit report
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy2.7'
      - run: pip install virtualenv
      - run: python -m virtualenv ./venv/
      - run: ./venv/bin/pip install autobahntestsuite==0.8.2
      - run: ./venv/bin/wstest --help
      #- run: wget https://downloads.python.org/pypy/pypy2.7-v7.3.17-linux64.tar.bz2
      #- run: tar fvx pypy2.7-v7.3.17-linux64.tar.bz2
      #- run: ./pypy2.7-v7.3.17-linux64/bin/pypy ./venv/bin/wstest --help
